selenium:
    container_name: selenium
    image: selenium/standalone-firefox-debug:2.53.0
    environment:
      - vncresolution=1600x900
    ports:
      - 127.0.0.1:4444:4444
      - 127.0.0.1:5900:5900
phpunit:
    container_name: phpunit
    image: albertalvarezbruned/phpunit
    links: 
      - selenium
    volumes:
      - $PWD/run.php:/src/run.php
